name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build for Linux (x86_64)
        run: GOOS=linux GOARCH=amd64 go build -o compareNames-linux-amd64 main.go

      - name: Build for Linux (arm64)
        run: GOOS=linux GOARCH=arm64 go build -o compareNames-linux-arm64 main.go

      - name: Build for macOS (x86_64)
        run: GOOS=darwin GOARCH=amd64 go build -o compareNames-macos-amd64 main.go

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release notes for ${{ github.ref_name }}" \
            ./compareNames-linux-amd64 \
            ./compareNames-linux-arm64 \
            ./compareNames-macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
